# Generated by Django 4.2.20 on 2025-07-21 17:05

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MICEInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Incentive', 'Incentive'), ('Conference', 'Conference'), ('Exhibition', 'Exhibition')], max_length=50)),
                ('attendees', models.PositiveIntegerField()),
                ('event_details', django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed event information and requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGOTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization_type', models.CharField(choices=[('NGO', 'Non-Governmental Organization'), ('Humanitarian', 'Humanitarian Organization'), ('Charity', 'Charity Organization'), ('Development', 'Development Agency'), ('Relief', 'Relief Organization'), ('Other', 'Other')], max_length=50)),
                ('travel_purpose', models.CharField(choices=[('Emergency Response', 'Emergency Response'), ('Field Operations', 'Field Operations'), ('Volunteer Coordination', 'Volunteer Coordination'), ('Project Implementation', 'Project Implementation'), ('Capacity Building', 'Capacity Building'), ('Monitoring & Evaluation', 'Monitoring & Evaluation'), ('Other', 'Other')], max_length=100)),
                ('number_of_travelers', models.PositiveIntegerField()),
                ('travel_details', django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed travel requirements and information')),
                ('sustainability_requirements', models.BooleanField(default=False, help_text='Do you require sustainable travel options?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('program_stage', models.CharField(choices=[('Registration & Training', 'Registration & Training'), ('Regional Round', 'Regional Round'), ('Global Round', 'Global Round'), ('Tournament of Champions', 'Tournament of Champions')], max_length=50)),
                ('number_of_students', models.PositiveIntegerField()),
                ('travel_details', django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed travel requirements and information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('include_travelling', models.BooleanField(default=False)),
                ('special_requests', django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='default', help_text='Any special requests or requirements', null=True)),
                ('paid', models.BooleanField(default=False)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-booking_date',),
            },
        ),
    ]
