# Generated by Django 3.2.20 on 2024-12-16 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='full_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookings',
            name='package_name',
            field=models.CharField(default='4-Day Tanzania Safari: Lake Manyara & Ngorongoro Crater', max_length=100),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookings',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='number_of_adults',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
