# Generated by Django 5.0.14 on 2025-07-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_destination_starting_price'),
        ('users', '0002_booking_guestbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_travel_style', models.CharField(blank=True, choices=[('budget', 'Budget Travel'), ('mid_range', 'Mid-Range'), ('luxury', 'Luxury'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('wildlife', 'Wildlife Safari'), ('beach', 'Beach & Relaxation')], max_length=50, null=True)),
                ('dietary_requirements', models.TextField(blank=True, help_text='Any dietary restrictions or preferences', null=True)),
                ('special_needs', models.TextField(blank=True, help_text='Any special assistance requirements', null=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications about bookings and offers')),
                ('marketing_emails', models.BooleanField(default=False, help_text='Receive marketing emails and travel deals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('package', 'Travel Package'), ('accommodation', 'Accommodation'), ('destination', 'Destination')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this bucket list item', null=True)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.accommodation')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.destination')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'accommodation'), ('user', 'destination'), ('user', 'package')},
            },
        ),
    ]
