# Generated by Django 3.2.20 on 2024-12-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241216_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbookings',
            options={'ordering': ('-booking_date',)},
        ),
        migrations.RemoveField(
            model_name='userbookings',
            name='package_name',
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
