# Generated by Django 5.0.14 on 2025-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_bucketlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('position_applied_for', models.CharField(choices=[('accountant', 'Accountant'), ('travel_consultant', 'Travel Consultant'), ('graphic_designer', 'Graphic Designer'), ('marketing_specialist', 'Marketing Specialist'), ('customer_service', 'Customer Service Representative'), ('tour_guide', 'Tour Guide'), ('operations_manager', 'Operations Manager')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('availability_date', models.DateField()),
                ('cover_letter', models.TextField(help_text="Tell us why you're interested in this position")),
                ('resume', models.FileField(help_text='Upload your resume (PDF preferred)', upload_to='job_applications/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notification_sent', models.BooleanField(default=False)),
                ('applicant_confirmation_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
