# Generated by Django 3.2.20 on 2025-02-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241217_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookings',
            name='travel_date',
        ),
    ]
