# Generated by Django 5.0.14 on 2025-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the email has been confirmed')),
                ('travel_tips', models.BooleanField(default=True, help_text='Receive travel tips and guides')),
                ('special_offers', models.BooleanField(default=True, help_text='Receive special offers and deals')),
                ('destination_updates', models.BooleanField(default=True, help_text='Receive destination updates')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('admin_notification_sent', models.BooleanField(default=False)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscription_date'],
            },
        ),
    ]
