# Generated by Django 3.2.20 on 2025-03-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userbookings_travel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MICEInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Incentive', 'Incentive'), ('Conference', 'Conference'), ('Exhibition', 'Exhibition')], max_length=50)),
                ('attendees', models.PositiveIntegerField()),
                ('event_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
