# Generated by Django 5.0.14 on 2025-08-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('application_status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing Applications'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=100)),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('responsibilities', models.TextField(help_text='Key responsibilities and duties')),
                ('salary_range', models.CharField(blank=True, help_text="e.g., 'KES 50,000 - 80,000' or 'Competitive'", max_length=100)),
                ('benefits', models.TextField(blank=True, help_text='Employee benefits and perks')),
                ('job_image', models.ImageField(blank=True, help_text='Job thumbnail image (recommended: 400x300px)', null=True, upload_to='job_listings/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField(blank=True, help_text='Last date to apply', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False, help_text='Show as featured job')),
                ('is_active', models.BooleanField(default=True, help_text='Display on careers page')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-featured', '-posted_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_listing',
            field=models.ForeignKey(blank=True, help_text='Specific job listing if applied through job detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.joblisting'),
        ),
    ]
