# Generated by Django 4.2.20 on 2025-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_miceinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization_type', models.CharField(choices=[('NGO', 'Non-Governmental Organization'), ('Humanitarian', 'Humanitarian Organization'), ('Charity', 'Charity Organization'), ('Development', 'Development Agency'), ('Relief', 'Relief Organization'), ('Other', 'Other')], max_length=50)),
                ('travel_purpose', models.CharField(choices=[('Emergency Response', 'Emergency Response'), ('Field Operations', 'Field Operations'), ('Volunteer Coordination', 'Volunteer Coordination'), ('Project Implementation', 'Project Implementation'), ('Capacity Building', 'Capacity Building'), ('Monitoring & Evaluation', 'Monitoring & Evaluation'), ('Other', 'Other')], max_length=100)),
                ('number_of_travelers', models.PositiveIntegerField()),
                ('travel_details', models.TextField()),
                ('sustainability_requirements', models.BooleanField(default=False, help_text='Do you require sustainable travel options?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('program_stage', models.CharField(choices=[('Registration & Training', 'Registration & Training'), ('Regional Round', 'Regional Round'), ('Global Round', 'Global Round'), ('Tournament of Champions', 'Tournament of Champions')], max_length=50)),
                ('number_of_students', models.PositiveIntegerField()),
                ('travel_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
