# Generated by Django 4.2.20 on 2025-07-14 20:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ngotravelinquiry_studenttravelinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miceinquiry',
            name='event_details',
            field=ckeditor.fields.RichTextField(help_text='Detailed event information and requirements'),
        ),
        migrations.AlterField(
            model_name='ngotravelinquiry',
            name='travel_details',
            field=ckeditor.fields.RichTextField(help_text='Detailed travel requirements and information'),
        ),
        migrations.AlterField(
            model_name='studenttravelinquiry',
            name='travel_details',
            field=ckeditor.fields.RichTextField(help_text='Detailed travel requirements and information'),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='special_requests',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Any special requests or requirements', null=True),
        ),
    ]
