# Generated by Django 5.0.14 on 2025-08-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_joblisting_jobapplication_job_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='alternative_phone_number',
            field=models.CharField(blank=True, help_text='Enter an alternative contact number (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(help_text='Enter your primary contact number (e.g., 254712345678)', max_length=20),
        ),
    ]
