# Generated by Django 5.0.14 on 2025-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobapplication_alternative_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(choices=[('Corporate Travel', 'Corporate Travel Management'), ('MICE', 'MICE Events & Conferences'), ('Group Travel', 'Group Travel Services'), ('Student Travel', 'Student Travel Programs'), ('NGO Travel', 'NGO Travel Solutions'), ('Holiday Packages', 'Holiday Packages'), ('Accommodation', 'Accommodation Booking'), ('Car Rental', 'Car/Van Rental Services'), ('General Inquiry', 'General Inquiry'), ('Partnership', 'Partnership Opportunities')], max_length=100)),
                ('message', models.TextField()),
                ('privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
