# Generated by Django 5.0.14 on 2025-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contactinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttravelinquiry',
            name='program_stage',
            field=models.CharField(choices=[('Registration & Training', 'Registration & Training'), ('Regional Round', 'Regional Round'), ('Global Round', 'Global Round'), ('Tournament of Champions', 'Tournament of Champions'), ('Model UN 2025-2026', 'Model UN 2025-2026')], max_length=50),
        ),
    ]
