# Generated by Django 5.0.14 on 2025-10-14 00:39

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_studenttravelinquiry_program_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title/heading for the popup', max_length=200)),
                ('image', pyuploadcare.dj.models.ImageField(help_text='Promotional poster/advertisement image (recommended size: 800x450px)')),
                ('inquiry_button_text', models.CharField(default='Inquire Now', help_text='Text for the inquiry/action button', max_length=50)),
                ('inquiry_url', models.URLField(blank=True, help_text='URL to redirect when inquiry button is clicked (leave blank for contact page)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup is currently active')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display priority (lower numbers show first)')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times the inquiry button has been clicked')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this popup has been displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Popup',
                'verbose_name_plural': 'Promotional Popups',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
