# Generated by Django 5.0.14 on 2025-11-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_promotionalpopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied_for',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('travel_consultant', 'Travel Consultant'), ('graphic_designer', 'Graphic Designer'), ('marketing_specialist', 'Marketing Specialist'), ('sales_marketing_executive', 'Sales & Marketing Executive'), ('customer_service', 'Customer Service Representative'), ('tour_guide', 'Tour Guide'), ('operations_manager', 'Operations Manager')], max_length=50),
        ),
    ]
