# Generated by Django 5.0.14 on 2026-08-24 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_sales_marketing_executive_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('public_review_permission', models.CharField(choices=[('yes', 'Yes, with my name'), ('anonymous', 'Yes, anonymously'), ('no', 'No, keep it internal')], default='no', max_length=20)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('recommend_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('transport_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('accommodation_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guide_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('activities_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('value_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('logistics_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('timeliness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('professionalism_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('coordination_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('enjoyed_most', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('short_testimonial', models.TextField(blank=True)),
                ('expectations', models.CharField(blank=True, choices=[('exceeded', 'Exceeded expectations'), ('met', 'Met expectations'), ('partly', 'Partly met expectations'), ('not_met', 'Did not meet expectations')], max_length=20)),
                ('travel_again', models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10)),
                ('future_destinations', models.TextField(blank=True)),
                ('has_media_to_share', models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip Feedback',
                'verbose_name_plural': 'Trip Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
