# Generated by Django 4.2.20 on 2025-07-21 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('lodge', 'Lodge'), ('resort', 'Resort'), ('guesthouse', 'Guest House'), ('airbnb', 'Airbnb')], default='hotel', max_length=20)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('price_per_room_per_night', models.PositiveIntegerField()),
                ('max_occupancy_per_room', models.PositiveIntegerField(default=2)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('amenities', models.TextField(help_text='Comma-separated list of amenities')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('destination_type', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('place', 'Place')], max_length=10)),
                ('description', models.TextField()),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adminside.destination')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True, help_text='Brief overview of the itinerary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('adult_price', models.PositiveIntegerField()),
                ('child_price', models.PositiveIntegerField()),
                ('inclusions', models.TextField(help_text="What's included in the package")),
                ('exclusions', models.TextField(help_text="What's NOT included in the package")),
                ('featured_image', pyuploadcare.dj.models.ImageField()),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('available_accommodations', models.ManyToManyField(blank=True, related_name='packages', to='adminside.accommodation')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('car', 'Car/Private Vehicle'), ('boat', 'Boat/Ferry'), ('cruiser', 'Cruiser')], max_length=20)),
                ('departure_location', models.CharField(max_length=200)),
                ('arrival_location', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price_per_person', models.PositiveIntegerField()),
                ('child_discount_percentage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('total_capacity', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transport_type', 'departure_time'],
                'indexes': [models.Index(fields=['transport_type', 'is_active'], name='adminside_t_transpo_cded95_idx'), models.Index(fields=['departure_location', 'arrival_location'], name='adminside_t_departu_28b009_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('travel_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to='adminside.package')),
                ('selected_accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='adminside.accommodation')),
                ('selected_travel_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='adminside.travelmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='available_travel_modes',
            field=models.ManyToManyField(blank=True, related_name='packages', to='adminside.travelmode'),
        ),
        migrations.AddField(
            model_name='package',
            name='main_destination',
            field=models.ForeignKey(help_text='Primary destination for this package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='adminside.destination'),
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_days', to='adminside.accommodation')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_days', to='adminside.destination')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='adminside.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='adminside.package'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='adminside.destination'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['main_destination', 'status'], name='adminside_p_main_de_218f08_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status', 'is_featured'], name='adminside_p_status_4e0cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryday',
            index=models.Index(fields=['itinerary', 'day_number'], name='adminside_i_itinera_639aba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('itinerary', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['destination_type', 'is_active'], name='adminside_d_destina_5b3d50_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['parent', 'is_active'], name='adminside_d_parent__291834_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['destination', 'is_active'], name='adminside_a_destina_717fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['accommodation_type', 'is_active'], name='adminside_a_accommo_b079a3_idx'),
        ),
    ]
