# Generated by Django 5.0.14 on 2025-07-22 00:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed accommodation description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed destination description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Detailed package description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='package',
            name='exclusions',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text="What's NOT included in the package"),
        ),
        migrations.AlterField(
            model_name='package',
            name='inclusions',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text="What's included in the package"),
        ),
    ]
