# Generated by Django 3.2.20 on 2024-12-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_destinations', to='adminside.destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='main_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_packages', to='adminside.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sub_destinations',
            field=models.ManyToManyField(blank=True, related_name='sub_packages', to='adminside.Destination'),
        ),
    ]
