# Generated by Django 5.0.14 on 2025-07-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_accommodation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for packages to this destination (in USD)', max_digits=10, null=True),
        ),
    ]
