# Generated by Django 3.2.20 on 2024-12-17 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_auto_20241216_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=1), 
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='child_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('package', 'day_number')},
        ),
        migrations.AddField(
        model_name='itinerarydescription',
        name='day_number',
        field=models.PositiveIntegerField(default=1),  # Provide a valid default
        ),
    ]

