# Generated by Django 5.0.14 on 2025-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_destination_starting_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_featured', 'is_active'], name='adminside_a_is_feat_c7c126_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['rating', 'is_active'], name='adminside_a_rating_32bfb5_idx'),
        ),
    ]
