# Generated by Django 3.2.20 on 2024-12-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_auto_20241217_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='itinerarydescription',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='itinerarydescription',
            name='day_number',
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='day_number',
        ),
    ]
