# Generated by Django 5.0.14 on 2025-08-06 11:12

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_accommodation_adminside_a_is_feat_c7c126_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
