# Generated by Django 3.2.20 on 2024-12-17 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_auto_20241217_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itinerarydescription',
            options={'ordering': ['day_number']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.AddField(
            model_name='itinerarydescription',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='adult_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='child_price',
            field=models.IntegerField(),
        ),
    ]
