# Generated by Django 5.0.14 on 2025-09-02 17:42

import django_ckeditor_5.fields
import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_destination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Deal title', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed deal description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 25.00 for 25%)', max_digits=5)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price before discount (in USD)', max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Price after discount (in USD)', max_digits=10)),
                ('valid_from', models.DateTimeField(help_text='Deal start date and time')),
                ('valid_until', models.DateTimeField(help_text='Deal end date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the deal is currently active')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured deals appear prominently')),
                ('featured_image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Main image for the deal', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_packages', models.ManyToManyField(blank=True, help_text='Packages included in this deal', related_name='deals', to='adminside.package')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
