# Generated by Django 3.2.20 on 2024-12-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_auto_20241217_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydescription',
            name='day_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itinerarydescription',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarydescription_set', to='adminside.itinerary'),
        ),
    ]
