# Generated by Django 4.2.20 on 2025-07-14 20:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_auto_20241217_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='hotel_description',
            field=ckeditor.fields.RichTextField(help_text='Detailed description of the accommodation with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dtn_description',
            field=ckeditor.fields.RichTextField(help_text='Detailed description of the destination with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='itinerarydescription',
            name='itinerary_description',
            field=ckeditor.fields.RichTextField(help_text='Day-by-day itinerary description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(default='NO DESCRIPTION ADDED', help_text='Detailed package description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='package',
            name='exclusive',
            field=ckeditor.fields.RichTextField(help_text="What's excluded from the package"),
        ),
        migrations.AlterField(
            model_name='package',
            name='inclusive',
            field=ckeditor.fields.RichTextField(help_text="What's included in the package"),
        ),
    ]
