# Generated by Django 4.2.20 on 2025-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief description of the post (max 500 characters)', max_length=500, null=True),
        ),
    ]
