# Generated by Django 4.2.20 on 2025-07-14 20:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Comment content with basic formatting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', help_text='Main blog content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='default', help_text='Brief description of the post', null=True),
        ),
    ]
