# Generated by Django 5.0.14 on 2025-07-22 00:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_comment_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, config_name='default', help_text='Brief description of the post', null=True),
        ),
    ]
