# Generated by Django 5.0.14 on 2025-07-22 00:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_comment_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Brief description of the post', null=True),
        ),
    ]
