# Generated by Django 5.0.14 on 2025-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from title)', max_length=1000, unique=True),
        ),
    ]
