# Generated by Django 5.0.14 on 2025-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for background processing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the campaign finished sending', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='emails_failed_count',
            field=models.IntegerField(default=0, help_text='Number of emails that failed to send'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='emails_sent_count',
            field=models.IntegerField(default=0, help_text='Number of emails successfully sent'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the campaign started sending', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='task_status',
            field=models.CharField(default='pending', help_text='Status of the background task', max_length=20),
        ),
    ]
