# Generated by Django 5.0.14 on 2025-10-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0002_emailcampaign_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for email personalization (JSON format). Leave empty if not needed.'),
        ),
    ]
